//
// !!! AUTOGENERATED FILE. DO NOT HAND-EDIT !!!
//

namespace omaha {

// PROXY_CLSID_IS_MACHINE = {760E6A51-8160-48A1-A074-DB397A770E9C}
const GUID kProxyClsidIsMachineGuid =
    {0x760E6A51, 0x8160, 0x48A1, {0xA0, 0x74, 0xDB, 0x39, 0x7A, 0x77, 0x0E, 0x9C}};

// PROXY_CLSID_IS_USER = {9F1A8620-DC48-4115-8B95-E76F26C228D6}
const GUID kProxyClsidIsUserGuid =
    {0x9F1A8620, 0xDC48, 0x4115, {0x8B, 0x95, 0xE7, 0x6F, 0x26, 0xC2, 0x28, 0xD6}};

}  // namespace omaha
